### ISSUE TITLE
Deployment of the server to GCP

### ISSUE THREAD

**Issue by glyxcode** [mganeko/mediasoup_sample_v2#1]
Thanks for the great example. Really liked it. 

Is it possible to deploy the server to the google cloud platform? Tried for a very long time, and had no success so far. The official docs say, the ip should passed to the rtcAnnouncedIPv4 parameter of the mediasoup server settings, but i'm really confused how this could be done because ip is changing every time. Do you have an idea, where the problem is and maybe give me a hint? :) Thanks!

**Comment by mganeko** [comment]
Thanks for your interest for this repo.

I think it is possible to deploy to Google Compute engine instance.
Please reserve static IP address for GCE instance.
https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address?hl=en

If you are trying to use GKE, you may need firewall service to use static IP address, and have to setup some port forwarding.
I am sorry that I am not familier with GKE.

I hope that you will find the way to get static IP address.

**Comment by glyxcode** [comment]
Thanks for your reply. :) Got it working already. Your hint points in the right direction. You have to setup a complete vm on google cloud comute engine, pass a static ip and use the rtcAnnouncedIPv4 parameter on mediasoup server settings. It doesnt work on google cloud app engine.  

(btw. when v3 of mediasoup is out, you could make a sample for this version too. Was very helpful for me as intial start, because all the other samples didnt work for me)
